### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by rsasaki0109** [hku-mars/decenterlized_loam#1]
Hello, very interesting project! Do you have an estimated release date for the code?

**Comment by ziv-lin** [comment]
Thanks for your interest in our work. 
I have busy schedules these months because I am currently working full time on the project of our ICRA-2021 paper.
By this, I have no time to clean up and publish our codes before 31 October 2020.
However, I promised **I will release our codes before 30 November 2020** once I free form the DDL.
Again, thank you for your interest and your patient.

**Comment by rsasaki0109** [comment]
Thank you.
